#!/bin/bash
set -e
service_name="oravo"
mkdir -p ~/.config/systemd/user
cp $service_name.service ~/.config/systemd/user


systemctl --user daemon-reload
systemctl --user enable $service_name.service
systemctl --user start $service_name.service
